// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BulkCapacityUpdateController from "./bulk_capacity_update_controller"
application.register("bulk-capacity-update", BulkCapacityUpdateController)

import CoverageRibbonController from "./coverage_ribbon_controller"
application.register("coverage-ribbon", CoverageRibbonController)

import EmailConfigController from "./email_config_controller"
application.register("email-config", EmailConfigController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationFieldsController from "./location_fields_controller"
application.register("location-fields", LocationFieldsController)

import ProfilePromptController from "./profile_prompt_controller"
application.register("profile-prompt", ProfilePromptController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
